version: '3.8'
services:
  dev_db:
    image: 'postgres:13'
    container_name: 'boots-shop'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest
    networks:
      - mynetwork
networks:
  mynetwork:
    external: true
